name: Build and deploy Python project to Azure Function App - azureresumeapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'main' # set this to the path to your Azure Function App project, defaults to the repository root
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Fetch resume data from Cosmos DB
        run: |
          export COSMOS_DB_ENDPOINT=<your_cosmos_db_endpoint>
          export COSMOS_DB_KEY=<your_cosmos_db_key>
          export COSMOS_DB_DATABASE=<your_cosmos_db_database>
          export COSMOS_DB_CONTAINER=<your_cosmos_db_container>
          
          python fetch_resume_data.py  # Replace with your script to fetch data from Cosmos DB

      - name: Prepare artifact for deployment
        run: |
          zip -r functionapp.zip . -x venv/\*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: function-app
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
     